# Generated by Django 5.1 on 2024-08-17 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
                "db_table": "cities",
            },
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="packages", verbose_name="Изображение упаковки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Упаковку",
                "verbose_name_plural": "Упаковки",
                "db_table": "packages",
            },
        ),
        migrations.CreateModel(
            name="Bouquet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="Цена"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=7,
                        verbose_name="Скидка",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                ("is_reserved", models.BooleanField(verbose_name="Зарезервировано")),
                ("is_sold", models.BooleanField(verbose_name="Продано")),
                ("created_at", models.TimeField(auto_now=True, verbose_name="Создано")),
                (
                    "images",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="bouquet_images",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "bouquet_type",
                    models.CharField(
                        choices=[("SC", "Онлайн-витрина"), ("IB", "Идеальный букет")],
                        max_length=100,
                        verbose_name="Тип букета",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.city",
                        verbose_name="Город",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.package",
                        verbose_name="Упаковка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Букет",
                "verbose_name_plural": "Букеты",
                "db_table": "bouquets",
            },
        ),
    ]
