# Generated by Django 5.1 on 2024-08-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_remove_colors_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bouquet",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
    ]
