# Generated by Django 5.1 on 2024-08-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_colors_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="BouquetPhotos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="bouqets/photos", verbose_name="Фото букета"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="bouquet",
            name="images",
        ),
        migrations.AddField(
            model_name="bouquet",
            name="photos",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="catalog.bouquetphotos",
                verbose_name="Изображения",
            ),
        ),
    ]
