# Generated by Django 5.1 on 2024-09-01 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_bouquet_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bouquet",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="catalog.package",
                verbose_name="Упаковка",
            ),
        ),
    ]
