# Generated by Django 5.1 on 2024-08-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_remove_bouquet_photos_remove_bouquetphotos_bouqet_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bouquetphotos",
            options={
                "verbose_name": "Фото букета",
                "verbose_name_plural": "Фото букетов",
            },
        ),
        migrations.AddField(
            model_name="bouquet",
            name="name",
            field=models.CharField(
                max_length=80, null=True, unique=True, verbose_name="Название"
            ),
        ),
    ]
