# Generated by Django 5.1 on 2024-08-19 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_bouquetphotos_options_bouquet_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bouquetphotos",
            name="bouquet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="photos",
                to="catalog.bouquet",
            ),
        ),
    ]
