# Generated by Django 5.1 on 2024-08-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="points",
            field=models.IntegerField(default=1, verbose_name="Баллы"),
            preserve_default=False,
        ),
    ]
