# Generated by Django 5.1 on 2024-08-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("QC", "Анкета заполнена"),
                    ("BC", "Букет собран"),
                    ("BU", "Доработка букета"),
                    ("WP", "Оплачивают заказ"),
                    ("PC", "Оплачено"),
                    ("CL", "Поиск курьера"),
                    ("T", "Передача курьеру"),
                    ("С", "Доставлено"),
                ],
                default=1,
                max_length=20,
                verbose_name="Статус",
            ),
            preserve_default=False,
        ),
    ]
