# Generated by Django 5.1 on 2024-08-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_payment_amount_remove_payment_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="user",
            new_name="profile",
        ),
    ]
