# Generated by Django 5.1 on 2024-08-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_rename_user_order_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=7, verbose_name="Сумма"
            ),
            preserve_default=False,
        ),
    ]
