# Generated by Django 5.1 on 2024-08-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_payment_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает оплаты"),
                    ("waiting_for_capture", "Удержание средств"),
                    ("succeeded", "Оплачено"),
                    ("canceled", "Возврат удержанных средств"),
                ],
                default="pending",
                max_length=40,
                verbose_name="Статус",
            ),
        ),
    ]
